-- Oracle Database schema definition for RIDES table
-- Connect as your application user and execute this script.

CREATE TABLE RIDES (
    RIDE_ID VARCHAR2(30) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    TIME_OF_RIDE TIMESTAMP NOT NULL,
    DISTANCE_KM NUMBER(5, 2) NOT NULL,
    DURATION_MIN NUMBER(5, 2) NOT NULL,
    PICKUP_ADDRESS VARCHAR2(500) NOT NULL,
    DROP_ADDRESS VARCHAR2(500) NOT NULL,
    TOTAL_AMOUNT NUMBER(8, 2) NOT NULL,
    RIDE_CHARGE NUMBER(8, 2) NOT NULL,
    BOOKING_FEES NUMBER(8, 2) NOT NULL,
    CONVENIENCE_CHARGES NUMBER(8, 2) NOT NULL,
    GATEWAY_CHARGES NUMBER(8, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) NOT NULL,
    CAPTAIN_NAME VARCHAR2(100) NOT NULL,
    VEHICLE_NUMBER VARCHAR2(30) NOT NULL,
    INVOICE_NO VARCHAR2(30) NOT NULL,
    STATE VARCHAR2(50) NOT NULL,
    CAPTAIN_FEE NUMBER(8, 2) NOT NULL,
    RIDE_CGST NUMBER(8, 2) NOT NULL,
    RIDE_SGST NUMBER(8, 2) NOT NULL,
    BOOKING_CGST NUMBER(8, 2) NOT NULL,
    BOOKING_SGST NUMBER(8, 2) NOT NULL
);

-- Index for faster search on customer name and ride time
CREATE INDEX IDX_RIDES_CUSTOMER_NAME ON RIDES(CUSTOMER_NAME);
CREATE INDEX IDX_RIDES_TIME ON RIDES(TIME_OF_RIDE);
